version: "3.9"

services:
  link-shortener-inmemory:
    build: ./
    command: ./link-shortener -db=inmemory
    ports:
        - "8000:8000"

  link-shortener-postgres:
    build: ./
    command: ./link-shortener -db=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5436:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data